clusterName: "opensearch-cluster"
nodeGroup: "single"

replicas: 1

persistence:
  enabled: true
  size: "5Gi"  # will increse size for real demo 
  storageClass: "standard" # "oci-bv" for real demo on oracle cloud 

opensearchJavaOpts: "-Xmx1g -Xms1g"

securityConfig:
  enabled: false

extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
  - name: DISABLE_SECURITY_PLUGIN
    value: "true"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

config:
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
    # DISABLE memory locking for Minikube environment
    bootstrap.memory_lock: false
    plugins.security.disabled: true

service:
  type: ClusterIP
  port: 9200

